In [1]:
# 최성훈
# 벡터의 내적

a1, a2, a3 = input("벡터1의 값 입력: 숫자사이 띄어쓰기 ").split()
print()
b1, b2, b3 = input("벡터2의 값 입력: 숫자사이 띄어쓰기 ").split()

a1 = eval(a1)
a2 = eval(a2)
a3 = eval(a3)
#a = ("({},{},{})".format(a1,a2,a3)) -> a = string
a =(a1,a2,a3)
print()
#print(a)
#print(type(a))


b1 = eval(b1)
b2 = eval(b2)
b3 = eval(b3)

print()
b = (b1,b2,b3)
print()

print("벡터의 내적")
print()

y = []
for i in range(3):
    k = a[i]*b[i]
    y.append(k)

    
print(a,"*",b,"=",sum(y))

벡터1의 값 입력: 숫자사이 띄어쓰기 1.1 2.2 3.3

벡터2의 값 입력: 숫자사이 띄어쓰기 0.9 1.1 2.3



벡터의 내적

(1.1, 2.2, 3.3) * (0.9, 1.1, 2.3) = 11.0


In [4]:
a = '1.1 2.2 3.3'.split()
print(a)
print(type(a))

['1.1', '2.2', '3.3']
<class 'list'>


In [5]:
# packing and unpacking 
# https://www.youtube.com/watch?v=UYTdjHYNqx8

a, b, c = '1.1 2.2 3.3'.split()
print(a)
print(type(a))

1.1
<class 'str'>


In [6]:
a = 1, 2, 3

print(a)
print(type(a))

(1, 2, 3)
<class 'tuple'>


In [8]:
import numpy as np

a1, a2, a3 = input("벡터1의 값 입력: 숫자들 사이에 빈칸을 주세요.").split()
b1, b2, b3 = input("벡터2의 값 입력: 숫자들 사이에 빈칸을 주세요.").split()

a1 = eval(a1)
a2 = eval(a2)
a3 = eval(a3)
a = np.array([a1,a2,a3])

b1 = eval(b1)
b2 = eval(b2)
b3 = eval(b3)
b = np.array([b1,b2,b3])

print()
print("벡터의 내적")
print()

print("a  : ", a)
print("b  : ", b)
print("ab : ", np.dot(a,b))

벡터1의 값 입력: 숫자들 사이에 빈칸을 주세요.1.1 2.2 3.3
벡터2의 값 입력: 숫자들 사이에 빈칸을 주세요.0.9 1.1 2.3

벡터의 내적

a  :  [1.1 2.2 3.3]
b  :  [0.9 1.1 2.3]
ab :  11.0


In [9]:
#박소현
# (for loop)

a = [1,2,3,4,5]
b = [ ]
for i in a:
    b.append(i+3)


print('문제')
print(a)
print('위에 주어진 항에 3을 더하여 계산하시오.')
print()
    
print('정답')
print(b)
print()

문제
[1, 2, 3, 4, 5]
위에 주어진 항에 3을 더하여 계산하시오.

정답
[4, 5, 6, 7, 8]



In [10]:
print('주어진 리스트의 각각의 항에 3을 더하여 계산하시오.')

a = [1,2,3,4,5]
print(a)

a = np.array(a)
b = a + 3
print(b)

주어진 리스트의 각각의 항에 3을 더하여 계산하시오.
[1, 2, 3, 4, 5]
[4 5 6 7 8]


In [7]:
# 최승준
# matrix transpose

x = [[1,0,0,0], [2,3,0,0], [4,5,6,0], [7,8,9,10]]
y = [[], [], [], []]
for i in range(len(x)) :
    for j in x:
        try: 
            y[i].append(j[i])
        except: 
            pass
        
print(x)
print(y)

[[1, 0, 0, 0], [2, 3, 0, 0], [4, 5, 6, 0], [7, 8, 9, 10]]
[[1, 2, 4, 7], [0, 3, 5, 8], [0, 0, 6, 9], [0, 0, 0, 10]]


In [8]:
import numpy as np

x = np.array([[1,0,0,0], [2,3,0,0], [4,5,6,0], [7,8,9,10]])
y = x.T
        
print(x)
print(y)

[[ 1  0  0  0]
 [ 2  3  0  0]
 [ 4  5  6  0]
 [ 7  8  9 10]]
[[ 1  2  4  7]
 [ 0  3  5  8]
 [ 0  0  6  9]
 [ 0  0  0 10]]


In [11]:
# 이미나

x = {'can', 'egg', 'bus', 'school', 'bus', 'korea'}
y = ['can', 'egg', 'bus', 'school', 'bus', 'korea']
print(x)
print(y)
print(type(x))
print(type(y))
print(len(x))    #원소의 개수
print(len(y))


x = {'a', 'b', 'c'}
y = {'c', 'd', 'e', 'f'}
print(x|y)   # 합집합
print(x&y)   # 교집합

{'can', 'bus', 'korea', 'school', 'egg'}
['can', 'egg', 'bus', 'school', 'bus', 'korea']
<class 'set'>
<class 'list'>
5
6
{'b', 'a', 'e', 'd', 'c', 'f'}
{'c'}


In [12]:
# 한제희

A = {'승': 45, '패':33, '무승부':0}
B = {'승': 44, '패':29, '무승부':5}
C = {'승': 41, '패':32, '무승부':5}

# https://www.w3schools.com/python/ref_func_eval.asp
# The eval() function evaluates the specified expression, 
# if the expression is a legal Python statement, it will be executed.
x = input('팀 이름 : ')
x = eval(x)

print('승률 =', x['승']/(x['승']+x['패']))

팀 이름 : A
승률 = 0.5769230769230769


In [13]:
x = 'print(55)'
eval(x)

55


In [9]:
# 박영욱

a = [m  for m in range(1,50) if m % 3 == 1]
b = [l  for l in range(1,50) if l % 3 == 2]
c = [n  for n in range(1,50) if n % 3 == 0]
print(a)
print(b)
print(c)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]


In [10]:
# 박영욱

u = [x for x in range(1,21)]
a = [a ** 2 + a for a in range(1,21) if (a ** 2 + a) % 3 == 0]
print(u)
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 12, 30, 42, 72, 90, 132, 156, 210, 240, 306, 342, 420]


In [12]:
# 박영욱

a = [x for x in range(1,11)]
b = [y for y in range(10,0,-1)]
print(a)
print(b)

# list concatanation
print(a+b)
print(b+a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [23]:
# 박영욱

import numpy as np

def time_period(length):
    g = 9.8
    T = 2 * np.pi * np.sqrt(length / g)
    return T

L = (15, 18, 21, 22.5, 25, 27)

for e in L:
    t = time_period(e/100)
    msg = 'Length: {} cm Time Period: {:.5f} s' 
    print(msg.format(float(e), float(t)))

Length: 15.0 cm Time Period: 0.77734 s
Length: 18.0 cm Time Period: 0.85154 s
Length: 21.0 cm Time Period: 0.91976 s
Length: 22.5 cm Time Period: 0.95205 s
Length: 25.0 cm Time Period: 1.00354 s
Length: 27.0 cm Time Period: 1.04291 s


In [14]:
# 강영수
# 피보나치

a = 1
b = 1
print(a, b, end=" ")
for i in range(3,101):
    c = a + b
    print(c, end=" ")
    a = b
    b = c

1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 1836311903 2971215073 4807526976 7778742049 12586269025 20365011074 32951280099 53316291173 86267571272 139583862445 225851433717 365435296162 591286729879 956722026041 1548008755920 2504730781961 4052739537881 6557470319842 10610209857723 17167680177565 27777890035288 44945570212853 72723460248141 117669030460994 190392490709135 308061521170129 498454011879264 806515533049393 1304969544928657 2111485077978050 3416454622906707 5527939700884757 8944394323791464 14472334024676221 23416728348467685 37889062373143906 61305790721611591 99194853094755497 160500643816367088 259695496911122585 420196140727489673 679891637638612258 1100087778366101931 1779979416004714189 2880067194370816120 4660046610375530309 7540113804746346429 

In [27]:
for i in range(3):
    print(i, end=' ')

0 1 2 

In [28]:
# 어정규

f = [1, 2, 3]  
print(f)
print(f[0] + f[2])

g = [1, 2, 3, ['a', 'b', 'c']]
print(g[0])
print(g[-1])
print(g[3])
print(g[-1][0])
print(g[-1][1])
print(g[-1][2])

h = [1, 2, ['a', 'b', ['Life', 'is']]]
print(h[2][2][1])

i = [1,2,3,4,5]
print(i[0:2])

a = [1, 2, 3, 4, 5]
b = a[:2]
c = a[2:]
print(b)
print(c)

a = [1,2,3,['a','b','c'],4,5]
print(a[2:5])
print(a[3][:1])

[1, 2, 3]
4
1
['a', 'b', 'c']
['a', 'b', 'c']
a
b
c
is
[1, 2]
[1, 2]
[3, 4, 5]
[3, ['a', 'b', 'c'], 4]
['a']
